# Site Information
site_name: Charli3 Dendrite
site_url: https://charli3-official.github.io/charli3-dendrite/
site_description: "Documentation for the Charli3 Dendrite project."
repo_url: https://github.com/Charli3-Official/charli3-dendrite
repo_name: 'Charli3-Official/charli3-dendrite'
edit_uri: https://github.com/Charli3-Official/charli3-dendrite/edit/main/docs/

theme:
  name: material
  palette:
    primary: 'red'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  locale: en
  include_sidebar: true
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

nav:
  - Home: index.md
  - DEXs:
      - Automated Market Maker:
          - amm_base.md
          - types.md
          - Modules:
              - Vyfi: vyfi.md
              - Minswap: minswap.md
              - Muesliswap: muesliswap.md
              - Spectrum: spectrum.md
              - Sundae: sundae.md
              - Wingriders: wingriders.md
      - Order Book:
          - order_book_base.md
          - Modules:
              - Axo: axo.md
              - Genius Yield: geniusyield.md
      - Core:
          - core_base.md
          - errors.md
  - Backend:
      - Backend Base: backend_base.md
      - Utils: utils.md
      - DBsync:
          - Models: dbsync_models.md
  - Data Classes:
      - Datums: datums.md
      - Models: models.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_root_toc_entry: false
            separate_members: true
            group_by_type: true
            shorten_signatures: true
          options:
            docstring_style: google  # Choose a consistent docstring style.
            class_attributes_style: italic  # Make class attributes italic for emphasis.
            bases_style: bold  # Make base class names bold.
            show_signature_annotations: true  # Display type annotations in signatures.
            show_if_empty: true  # Always show class/method even if docstring is empty.
watch:
  - src
extra:
  version: 1.0
extra_css:
  - css/custom.css
