name: Pre-commit

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Cache the pre-commit environment
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pypoetry
          key: ${{ runner.os }}-precommit-${{ hashFiles('**/.pre-commit-config.yaml', '**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-precommit-
            ${{ runner.os }}-precommit-${{ hashFiles('**/.pre-commit-config.yaml') }}-
            ${{ runner.os }}-precommit-${{ hashFiles('**/poetry.lock') }}-

      - name: Run pre-commit
        run: pre-commit run --all-files
